### ISSUE TITLE
Wrong results when not using brackets

### ISSUE THREAD

**Issue by LordCaox** [FlorianRappl/YAMP#12]
Hi Florian

I've been using YAMP for a while and I really think it's a very good solution because it provides a lot of flexibility for calculating non-hardcoded equations. 

However I noticed an issue when calculating simple equations without using brackets. 
The problem is the number it returns is not correct, I think the reason is that YAMP is not always respecting the priority in the operators (multiplications and divisions before additions and substractions), and when this happens the only easy way to resolve it is adding brackets even when mathematically it's unnecessary, otherwise the number looks totally wrong.

Here an example
Equation: 0.212410080106903 * 500-0.00654415361812242 * 500-0.0337905933677912 * 500-0.182007882231707 * 500+131.208072980527
Expected result: 126.241798425
YAMP result: 160.0323917929594

YAMP calculates it good when adding brackets:
(0.212410080106903 * 500)-(0.00654415361812242 * 500)-(0.0337905933677912 * 500)-(0.182007882231707 * 500)+131.208072980527 

Do you think this can be fixed?

Thanks

**Comment by LordCaox** [comment]
Sorry I'm not  sure why multiplication symbol is not being shown in this webpage, before

**Comment by FlorianRappl** [comment]
Hm this may be an old bug, because I can remember that a similar issue was already tracked a while ago. Which version are you using?

I will try investigating / updating (if its already fixed in the source; but not in the package).

**Comment by FlorianRappl** [comment]
I added a test - this behavior is already fixed (as I thought). Also the current NuGet package is at version 1.4.0 - this should be the one without this bug. Can you confirm this ?

**Comment by LordCaox** [comment]
Thanks Florian, I apologize because I was still using version 1.3
I confirm version 1.4 is working fine, thank you for your time, keep up the good work :+1:

**Comment by FlorianRappl** [comment]
Great to hear! :+1:
