### ISSUE TITLE
New NuGet Package

### ISSUE THREAD

**Issue by ryanthompson0123** [FlorianRappl/YAMP#14]
Could you please push the latest changes to NuGet?

I'm working on a project that needs the PCL target change from PR #10 

Thanks!

**Comment by FlorianRappl** [comment]
For the PCL there is the [YAMP Portable](https://www.nuget.org/packages/YAMP.Portable/) package. So this one has already been released. Nevertheless, e.g., #13 is not solved in both of these (the normal and the portable version) packages. I'll try to update tonight!
