### ISSUE TITLE
Object identifiers parsing in wrong order with certain operators

### ISSUE THREAD

**Issue by SigmaEpsilonChi** [FlorianRappl/YAMP#15]
With the new object system, identifiers like foo.bar.x will not be parsed as a unit with certain operators. For example, 
`3-foo.bar.x`
will be parsed as
`(3-foo).bar.x`
Which throws an operator exception since - cannot be used on an object. However,
`3-(foo.bar.x)`
will parse correctly.
`3+foo.bar.x`
parses correctly too, but
`3*foo.bar.x`
`3^foo.bar.x`
`-foo.bar.x`
all do not parse.

**Comment by FlorianRappl** [comment]
I think this is due to the operator precedence (I actually forgot to assign a number...). I will take care of that!

Thanks for the report.

**Comment by FlorianRappl** [comment]
This has been solved. An updated NuGet package is on the way!
