### ISSUE TITLE
Parser does not provide a way to check if all symbols are found in current query

### ISSUE THREAD

**Issue by SigmaEpsilonChi** [FlorianRappl/YAMP#16]
The parser offers properties for ErrorCount and HasErrors which are useful to avoid parse errors, but does not include YAMPSymbolMissingException. In applications where the parser runs as the user types it, Missing Symbol Exceptions are thrown continuously until the full symbol name is typed in. It would be helpful either to have a separate property for SymbolsMissing or just for these exceptions to be included in the ErrorCount.

**Comment by FlorianRappl** [comment]
Hm, that a symbol is missing can only be determined if you actually want to run the application. If you only parse it, it is not detected. Therefore I can only assume that you actually continuously run the application, right?

**Comment by SigmaEpsilonChi** [comment]
Every time the a function changes I filter out simple values with
float/bool.TryParse(). I then Parse() the leftovers, and Run() those
functions every frame.

I suppose it makes sense that missing symbols can only be determined once
Run() is given a dictionary of symbols. Right now I just catch the
MissingSymbolExceptions which works fine, but it would be very helpful to
be able to tell the user which symbols are not valid in their function. Is
there currently a way to get that information that I'm not seeing?

**Comment by FlorianRappl** [comment]
Nope, and I am not sure how much effort it is. If its less than ~2 hrs I can provide it, otherwise it would be beyond my capacities. But MAGES will provide such capability for sure :smile: !

**Comment by SigmaEpsilonChi** [comment]
Okay, don't worry about it then. Thanks anyway!
