### ISSUE TITLE
Repeated BinaryOperatorMappings are added to the mapping list, reducing performance

### ISSUE THREAD

**Issue by nhenriques** [FlorianRappl/YAMP#18]
RangeValue and MatrixValue (for example), share the same `RegisterOperators()` override.
That function will be called twice, and so the operators will register the same functions more than once in the mappings collection.
I've tested a quick fix, resulting in around 10% speed increase on BenchmarkKind.Standard.
This quick fix involved replacing `"List<BinaryOperatorMapping>"` by a new class, which overrides (hides) method `"Add(BinaryOperatorMapping op)"`, and skip adding the instance if an "equal" BinaryOperatorMapping is already in the list.

    internal class BinaryOperatorMappingList : List<BinaryOperatorMapping>
    {
        public new void Add(BinaryOperatorMapping op)
        {
            for (int i = 0; i < Count; i++)
            {
                //Don't repeat equal operators
                if (this[i].IsEqual(op))
                    return;
            }
            base.Add(op);
        }
    }

Several classes  (MemberOperator, MinusOperator, ...) should be changed to use the new class.

"Equality" on BinaryOperatorMapping was checked for the 3 fields. Something like:
```
        public bool IsEqual(BinaryOperatorMapping obj)
        {
            if (obj == null)
                return false;
            return (_arg1 == obj._arg1) && (_arg2 == obj._arg2) && (_f == obj._f);
        }

```
Thanks.
Nuno

**Comment by FlorianRappl** [comment]
Sounds good!
