### ISSUE TITLE
Difference between NeqOperator "~=" and (the inexistent) "!=" leads to confusion

### ISSUE THREAD

**Issue by nhenriques** [FlorianRappl/YAMP#20]
Starting note: I know there is no "!=" operator.

I noticed some nunit tests pass ok, but with "wrong" expressions.
For example, the following (Engine) Test passes with flying colors!
```
        [Test]
        public void ParseForStatement()
        {
            Test("for(k = 0; k != 2; k++) { }", false);
        }
```
But, has one may notice, this particular test "should" have be written as:
```
        [Test]
        public void ParseForStatement()
        {
            Test("for(k = 0; k ~= 2; k++) { }", false);
        }
```
In these (YAMP.Core.Tests) Engine nunit tests, the expression is only Parsed, it's not Evaluated.
Actually, the first one (...`k != 2`...) will fail during Evaluation with:
```
   An exception during runtime occured:
   The left side of an assignment must be symbol.
```
which lead me to... what the heck is the "k != 2" being parsed into ?!
I would expect this to throw a parse error, but it seems not.

It seems that "k!" is k-factorial, and whatever comes after is... "=2". what?!

So...
Although "any" test is a "good" test, I would replace the nunit test for the k~=2 version, or (better) make sure that "k != 2" throws an error (unless there is a good reason for not doing so).

I'm a C,C++,C# guy... and new to YAMP, so it's rather confusing... but what does this expression mean to the parser: "a!=0" ?

The expression "a=2; a~=1" is fine for the parser and evaluation...
The "a=2; a!=1" is ok to the parser, but blows up during evaluation.

So, is there a reason to this behavior?
If one simply implements the operator "!=" equal to the "~=" operator, would that break anything?

Many thanks for this excellent library!
Nuno

**Comment by FlorianRappl** [comment]
As you have noticed YAMP introduces the factorial operator `!`. Therefore we either have to take `!=` as a fixed expression (possible) or we introduce a new negation operator. I decided to go for the latter, as this avoids an ambiguity (I can't use `!` for the classical negation as this is taken already, so I took the bitwise negation operator `~` which does not make much sense in YAMP).

To answer your questions:
* I think one could implement the operator, but there are some subtle issues (and as YAMP tries to stay close to MATLAB I've picked the same operator `~=`)
* As YAMP does not know during compile-time what kind of element is on the left-side the capability of assignment is evaluated during runtime - hence parsing is fine, but evaluating is not

Hope this helps!

**Comment by nhenriques** [comment]
Thanks for your explanation.
I'm happy with the "~=" choice. As I would be with "!=", or even "<>".
It's just a pitty that this particular symbol combination "!=", which is so common in current programming languages, is confused with factorial and, particularly on this case, it's not caught by the parser...
Fortunately, at least it's caught during runtime. There could be nothing worse than evaluating the "wrong" / misleading expression...

If there would be some kind of "alias" to the operators implemented on yamp, i would probably use it to get both "~=" and "!=" do the same, and actually avoiding this factorial-thing. Like I said - unless this would break any other expression or feature already valid on yamp.

It seems there is no "alias", so in this case, I would just "fix" the ParseForStatement() nunit test. It's a misleading test case.
I stumbled upon it because I was trying to find examples of Keyword expressions, and found that one...
```
> for(k = 0; k != 2; k++) { }
An exception during runtime occured:
The left side of an assignment must be symbol.
```
My fault, but It took some experiments to even understand where the error was...
And this is a small expression :-)

Which leads me to another thing...
Is there a way to "output" the full expression tree in some readable text format?

Thanks.
Nuno

**Comment by FlorianRappl** [comment]
Yes, makes sense. I'll insert the alias and adjust the unit test (just to have the primary operator in place; even though the current unit test would then also make sense).
