### ISSUE TITLE
Functions with object's context

### ISSUE THREAD

**Issue by nhenriques** [FlorianRappl/YAMP#21]
Hi
I'm trying to implement a pattern like this:
```
set1 = CreateSet(1,2,3,5,10)
filteredSet = set1.Where("some expression", "someoptionalparameter")

```
"CreateSet" can be implemented as a function, with nparams, and returning a "SetObj" object.
I've already implemented that part (creating the "SetObj" and the function "CreateSet")
There was some "impedance" to get accustomized to YAMP, but it wasn't too difficult.

Now, I need to implement the "Where" function, if possible.
Like in a "object.Method" or "object.Property" pattern, this would mean the "Where" function has to have access to the "state/context/leftPartObject" on which it runs - in this case, the "setAccessor" object.
What should be the correct way of doing this?
Things i've tried:
- Extend the "MemberOperator" to support my "SetObj" - Can't do, MemberOperator is not public.
- Create a new "." MyMemberOperator - it seems it's not possible. The symbol is already in use (and I had to modify a lot of classes, turning them Public, to even add the new operator).
- Inherit my SetObj from "ObjectValue" and try to override some useful methods  - not possible, it's sealed.

Maybe the best solution is already biting me, but i'm not seeing it.

Note: I could use a different approach, something like:

`filteredSet = Where(set1, "some expression", "someoptionalparameter")`

But, if possible (it could be useful for many other derivatives), i'd like to try the object.Method approach.

Can you advise me on this?

Many Thanks,
Nuno.

**Comment by FlorianRappl** [comment]
Objects in YAMP a more like structs in C - they only aggregate data and do not have features such as member functions (= methods) that are called with an implicit first argument.

But that does not mean we cannot change / extend it. So right now we can do:

```C
obj = object();
obj.x = 5;
obj.getX = () => obj.x;
x = obj.getX(); //5
```

We actually would like to do:

```C
obj = object();
obj.x = 5;
obj.getX = () => this.x;
x = obj.getX(); //5
```

How about adding a helper function `addMember` to enable writing:

```C
obj = object();
obj.x = 5;
addMember(obj, "getX", () => this.x);
x = obj.getX(); //5
```

Potentially, the special object created by calling `CreateSet` should already come with the described methods (or at not known upfront). I think it would be better to use an `IDictionary` in the `ObjectValue` to allow re-implementing the whole internal behavior.

What are your thoughts? Is this similar to what you try to achieve or did I misunderstand the request?

**Comment by nhenriques** [comment]
Thank you, Florian.
I have to digest your answer...

I still don't fully understand your example: `addMember(obj, "getX", () => this.x);`
It's not clear to me if the "() => this.x" is a dotnet lambda or a YAMP lambda.
If it's a YAMP lambda, it would need the "this.x" already working, right? Or is the expression passed to dotnet, and evaluated inside it?
I have to test it, for me this is still a moving ground...

But, as I read it, right now there is no way of having a "this" state passed to functions (any type of them).
But I see a few functions (actually, the SystemFunctions) that "already" receive some Context (ParseContext).
I didn't use it yet, but that allows access to the Variables/_variables Dictionary, which are documented as "(local) variables", whatever that (local) means.

Maybe there would be a new interface to declare and be implemented by specific functions which would receive the "left" object / part on which the "." operator is applied.
(Maybe the dotoperator/memberoperator would have access to the "left" part/object, and pass it to the "right" part...)
Normal functions would stay as they are right now (more or less like a dotnet static function), and others would receive some kind of "last" object state (YAMP Value) as an argument.
Also, may be the objects themselves would need also to implement a specific GetState() method/interface, but i don't know if that would actually be needed.
Of course, I'm not trying to re-create any kind of OO/Polimorphic/Inheritable language...
It may be too simple, or too difficult, but I'm just trying to apply a "normal" function to a YAMP.Value type, with variable parameters (like any ArgumentFunction).
And this would have to be really a Function (with parameters), not only a "Get/Set Property".

I'll keep working.

As a side note, I'll explain more of what i'm trying to implement (the Real case)...
It's a work in progress, and I'll try to get the maximum of YAMP, for obvious reasons, and implement the rest as usual :-)

- Use YAMP as a "rules engine" for some Apps... The "formulas" are easy to write (for the Final user), and very powerfull.
- I need some kind of Set operations (intersect, union, except...)
- Those sets need to support String elements, so extending Matrix/Range (only Numerics) to add those functions seems interesting but is not an option, without breaking a lot of stuff.
- Probably I'll use the dotnet HashedSet to support the new (YAMP style) ObjSetValue.
- This specific case, from which I extracted the
```
set1 = CreateSet(1,2,3,5,10)
filteredSet = set1.Where("some expression", "someoptionalparameter")
```
is a more complex one...
Actually, in a use case i'm working on, a more specific example could be something like this:
```
set1 = CreateSet(1,2,3,5,10) //Only scalar values (integers, strings...)...
//... don't need to generalize as of now, but i would not be difficult, i think
filtset1 = set1.WhereEach(isOddMumber)
filtset2 = set1.WhereEach(isMultipleOf, 5)
...
```
For now, I don't care of the specific implementation of "isOddNumber" or "isMultipleOf"... That's not the problem. They could be even passed as a string, and evaluated case by case inside WhereEach().
What I think is needed is to implement a "WhereEach" function getting a reference to the "set1" content, and apply somekind of code to it and, in this case, return a new Set.
This would allow expressions like:
`setC = (set1 + set2) ^ (set3 / set4)`
or, written in other way...
`setC = (set1.union(set2)).intersect(set3.except(set4))`
or (feasable right now...)
`setC = intersect(union(set1, set2), except(set3, set4))`

(I would - and I think "my" users - prefer the first form!)

So, one of the problems in hand is writing a good "set" operations/operators
the other one is allowing (some) objects to have (some) nonstatic functions working on them.

Thanks

**Comment by nhenriques** [comment]
There is maybe-not-so-small detail on this...
Those functions could be implemented (if interesting) as in C++ "const" functions.
The meaning of this is they don't necessarily have to have access to modify the "this" object.
They could even get a reference to a Copy of the object, so allowing some protection on the object itself.
In the pseudo-examples that I gave for the Sets, they make use of the "this" object, but returning a new Set, without modifying the this/self object.

Thanks.

**Comment by FlorianRappl** [comment]
I think in your case providing your own data type (`*Value`) seems to be the best option. But this means coming up with your operators and bending the member operator to your will, which is a use-case that was never foreseen (actually in the first version of YAMP there was not even a member operator - or objects).

The code I've written above was all YAMP. The idea behind the `addMember` function was that it takes the function and "re-wires" any occurrences of the `this` to the passed object (in this case `obj`). The re-wiring is quite simple as it just needs to wrap the function in another function that sets the `this` with the captured `obj`.

I will check if registering member operators is possible (should be!) and makes sense (I think it does, as we see).

**Comment by nhenriques** [comment]
Hi again, Florian.
Can you have a look on my SETs branch?

https://github.com/nhenriques/YAMP/tree/SETs
see: [readme](https://github.com/nhenriques/YAMP/blob/SETs/YAMP.Sets/readme.markdown)
see: [tag v0.9beta](https://github.com/nhenriques/YAMP/releases/tag/v0.9-beta)

I've published a lot of code, with some "enhancements" I "had" to do to YAMP.Core, along with my implementation of a SetValue object.

This library makes use of "MemberFunctions", to emulate object method calls.
Also, i've override some operators in my library, and created a new one.
I've supplied also a Tests project, along with my Full solution "YAMPSets.sln" at root.

I made incremental commits to enable a small history of modifications to YAMP.Core.

ATTENTION: As explained in some places, i had to switch the Level (priority) of the ArgsOperator and MemberOperator. It didn't break any existing test, but that's the major change that I think may break other's code. Please take a run on all other tests you may have, to check this.
Without this change, a simple expression like "a.fn() + 1" would break the parser (Stack Empty).

Note: I didn't commit the small change to YAMP.App.Repl, to reference and load the plugin, to be able to use it in your console. I recommend everyone to do it, besides running all the provided tests.

Thanks,
Nuno

**Comment by FlorianRappl** [comment]
I only had the chance of looking at the changes briefly. What I saw is quite cool - so thanks.

If you just make a PR I can have a look at the diffs in a more convenient manner. Should I make the extension `YAMP.Sets` available on NuGet as with the other add-ons?

I guess YAMPSets.sln is essentially YAMP.sln with YAMP.Sets and YAMP.Sets.Tests projects. In this case you can just replace YAMP.sln with the content of YAMPSets.sln.

**Comment by nhenriques** [comment]
Done!
Hope everyone likes it.

And, yes, please include it along with the other plugins in your main project.
I've modified the YAMP.App.Repl to include the Sets plugin.

Nuno

**Comment by FlorianRappl** [comment]
That's a very good change.

BTW: Are you aware of [Mages](https://github.com/FlorianRappl/Mages)? It is the official successor to YAMP and it is taking shape. Member functions are easily done in Mages, but operators are not yet so expandable. Nevertheless, its probably worth checking it.

**Comment by nhenriques** [comment]
I've just had a (very) quick look the description a while ago when checking for available expression evaluators, but then decided to extend on YAMP, just for the reason it was "declared" stable.
I'll have a look at it.
Thanks.

**Comment by nhenriques** [comment]
Nope... I must have confused with anything else.

**Comment by FlorianRappl** [comment]
Everything updated ...

[YAMP](https://www.nuget.org/packages/YAMP)
[YAMP.Sets](https://www.nuget.org/packages/YAMP.Sets/)
[YAMP.Physics](https://www.nuget.org/packages/YAMP.Physics/)
[YAMP.IO](https://www.nuget.org/packages/YAMP.Io/)
[YAMP.Sensors](https://www.nuget.org/packages/YAMP.Sensors/)

I'll update the assembly info such that next time *Sets* will appear as * YAMP.Sets* in the NuGet search as well.

**Comment by nhenriques** [comment]
Great!
I've tested it just now, with only the Sets and core, from NuGet.
Attached is a simple Windows test Form.

[TestYAMPSets.zip](https://github.com/FlorianRappl/YAMP/files/302699/TestYAMPSets.zip)

**Comment by FlorianRappl** [comment]
Very cool!
