### ISSUE TITLE
StringValue should implement "equality"

### ISSUE THREAD

**Issue by nhenriques** [FlorianRappl/YAMP#22]
Hi Florian,

StringValue doesn't implement "Equals" or "GetHashCode".
ScalarValue does both.

I've noticed it while trying to use a HashSet of StringValues (to implement a new "Set" object)...

Small example:
```
                var set = new System.Collections.Generic.HashSet<StringValue>();
                set.Add(new StringValue("1"));
                set.Add(new StringValue("1"));
                int count = set.Count;
```
Count should be == 1, but it's 2.

As StringValue encapsulates a string (like ScalarValue encapsulates a numeric), it seems reasonable that it should be behave like their encapsulated values.

Something like this may be appropriate (be my guest)
```
        #region Comparison
        /// <summary>
        /// Is the given object equal to this.
        /// </summary>
        /// <param name="obj">The compare object.</param>
        /// <returns>A boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is StringValue)
            {
                var sv = obj as StringValue;
                return sv._value == _value;
            }

            if (obj is string || obj == null)
                return (string)obj == _value;

            return false;
        }

        /// <summary>
        /// Computes the hashcode of the value inside.
        /// </summary>
        /// <returns>The hash code.</returns>
        public override int GetHashCode()
        {
            return _value == null ? 0 : _value.GetHashCode();
        }
        #endregion

```

Thanks,
Nuno

**Comment by FlorianRappl** [comment]
If you want it to be implemented please file a PR.

**Comment by nhenriques** [comment]
I'll do it.
As it's only needed mainly because of Hash functions, I'll do it along with my (suggested) implementation of some SetValue object and operations.
But it will take some time for me. I'm also working on a few other things (yamp related, also).
Thank you again.
Nuno

**Comment by FlorianRappl** [comment]
Sure, thanks - much appreciated!

**Comment by FlorianRappl** [comment]
I think this is fulfilled with PR #23 (which also solves #21).

**Comment by nhenriques** [comment]
I've added an explicit test right now, on the Sets.Tests.
Didn't try this test now without the "equality" fix, but I tested it previously and failed.
