### ISSUE TITLE
[feature request] large number support

### ISSUE THREAD

**Issue by jhdxr** [FlorianRappl/YAMP#24]
I'm using wox, which rely on YAMP to calculate the numbers. I found YAMP cannot deal with the large numbers (see Wox-launcher/Wox#1022 ), for example, `1476716883801-1476716304118`, the result is 0, which is obviously wrong. I'm excepting YAMP could give the correct result, 579683, or just throw an exception saying the number is out of range.

**Comment by FlorianRappl** [comment]
Hi @jhdxr - thanks for your input. I would love to add this, but YAMP is no longer developed. The official successor is [MAGES](https://github.com/FlorianRappl/Mages). I would say the same thing ("support very large numbers") could be said about MAGES, as it also only uses `double` values underneath, however, the given expression works fine (as an example).
