### ISSUE TITLE
current nuget version doesn't work on Windows XP

### ISSUE THREAD

**Issue by DanWBR** [FlorianRappl/YAMP#25]
Although YAMP can be added to a .NET 4.0 project, it doesn't work on Windows XP because it cannot find "System.Core" version 2.0.5.0:

System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The type initializer for 'YAMP.ParseContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'YAMP.ParseContext' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at YAMP.Plugin.Instantiate[T](Elements elements, Type type, Type[] interfaces)
   at YAMP.Plugin.Install()
   at YAMP.Elements.RegisterAssembly(ParseContext context, Assembly assembly)
   at YAMP.ParseContext..ctor(IDictionary`2 shadowVariables)
   at YAMP.ParseContext..cctor()
   --- End of inner exception stack trace ---
   at YAMP.ParseContext..ctor()
   at YAMP.Parser..ctor()

**Comment by FlorianRappl** [comment]
YAMP is not maintained any more. Unless you can show that this is in fact an actual problem with YAMP (which I doubt, sounds more like the respective .NET version is not installed) I believe that going for [MAGES](https://github.com/FlorianRappl/Mages) is a better choice.

**Comment by DanWBR** [comment]
I believe that this is the same problem as related on https://github.com/beto-rodriguez/Live-Charts/issues/212

Nevermind, I 've removed YAMP from my project.  Thanks.
