### ISSUE TITLE
Nullreference Exception using in Unity under il2cpp

### ISSUE THREAD

**Issue by socket220** [FlorianRappl/YAMP#26]
I just tried to build project in Unity by mono and il2cpp. In mono all works correctly, but using il2cpp I get exception:

NullReferenceException: Object reference not set to an instance of an object.
  at YAMP.Plugin.Install () [0x00000] in <00000000000000000000000000000000>:0 
  at YAMP.Elements.RegisterAssembly (YAMP.ParseContext context, System.Reflection.Assembly
assembly) [0x00000] in <00000000000000000000000000000000>:0 _
  at YAMP.ParseContext..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] shadowVariables) [0x00000] in <00000000000000000000000000000000>:0 
  at YAMP.ParseContext..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at YAMP.Parser..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Main.Start () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'YAMP.ParseContext' threw an exception.
  at YAMP.Parser..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Main.Start () [0x00000] in <00000000000000000000000000000000>:0

Is any idea how to solve that?
P.S. I'm testing a lot of math parser libraries, so YAMP gives the heighest performance. Thank you!

**Comment by FlorianRappl** [comment]
Hi @socket220 thanks for reporting this.

YAMP is unfortunately no longer maintained. Is there some reason for you not to use [MAGES](https://github.com/FlorianRappl/Mages)? It is the official successor from my side. It should also give much better performance than YAMP... (but please makre your own tests; if you see something different then feel free to report the test case(s) to improve the situation).

**Comment by socket220** [comment]
I just have tested today performances between YAMP and Mages.
There are my tests:
[https://i.imgur.com/i5ivxfL.png](url)
1-st test implements 10^6 evaluations list of string expressions with basic math operations;
2-nd test implements 10^6 evaluations list of string expressions with some function, just sets by lambda for example;
3-rd test implements 10^6 evaluations of some compiled expression. In my case it is just [0] element from 2-nd test;
4-th test implements 10^6 evaluations with some large string with library implemented functions.

**Comment by FlorianRappl** [comment]
Cool thanks for sharing. Can you tell me how you use Mages? There are different options and you can, e.g., activate caching (so to separate "compiling" from "execution", which is not possible with YAMP).

**Comment by socket220** [comment]
Thanks for reply.
In 1, 3 and 4 tests I use Mages like that:

```cs
var mages = new Mages.Core.Engine();
mages.Interpret(expression[idx]);
```

In 2-nd test uses code:

```cs
var mages_functions = new Mages.Core.Engine();
var func = new Func<int, int>(a => a * 2);
mages_functions.SetFunction("FUNC", func);
var precompiled_expr = mages_functions.Compile(expressions_f[0]);
precompiled_expr();
```

I suppose, is that such caching that you meant, right? Or have I alternative way somehow to do that?

**Comment by FlorianRappl** [comment]
Yes, as long as you have `precompiled_expr` only in your loop / hot path (otherwise, of course, you defeat the purpose of having the function compiled already).

**Comment by socket220** [comment]
Oh, I forgot to notice that I use `precompiled_expr();` evaluation in loop already.

**Comment by socket220** [comment]
As I understand, use I library correctly in that way, right?

**Comment by FlorianRappl** [comment]
I would say yes, even though I don't know you use case / what you are after. But for general usage this is exactly how you do it. Hope this library helps you and brings you joy!

**Comment by socket220** [comment]
Thank you for help!
